name: VyOS Nightly Build

on:
  workflow_dispatch:
    inputs:
      gcp_project_id:
        description: "GCP Project ID where the image will be uploaded"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ github.event.inputs.gcp_project_id }}
      GCS_BUCKET: vyos-images
    steps:
      - name: Checkout vyos-build repository
        uses: actions/checkout@v4
        with:
          repository: vyos/vyos-build
          path: vyos-build

      - name: Build VyOS ISO
        run: |
          docker run --rm --privileged -v $(pwd)/vyos-build:/vyos -w /vyos vyos/vyos-build:current bash -c "sudo ./build-vyos-image generic --architecture amd64"

      - name: Upload VyOS ISO
        uses: actions/upload-artifact@v4
        with:
          name: vyos-nightly-iso
          path: vyos-build/build/*.iso
          
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Upload image to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: vyos.iso
          destination: gs://${{ env.GCS_BUCKET }}/vyos-${{ github.run_number }}.iso
          project_id: ${{ env.PROJECT_ID }}
