name: VyOS Nightly Build

on:
  workflow_dispatch:
    inputs:
      gcp_project_id:
        description: "GCP Project ID where the image will be uploaded"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ github.event.inputs.gcp_project_id }}
      GCS_BUCKET: vyos-images-v1
    steps:
      - name: Checkout vyos-build repository
        uses: actions/checkout@v4
        with:
          repository: vyos/vyos-build
          path: vyos-build

#      - name: Build VyOS ISO
#        run: |
#          sudo docker run --rm --privileged -v $(pwd)/vyos-build:/vyos -w /vyos vyos/vyos-build:current bash -c "sudo ./build-vyos-image generic --architecture amd64"
     
      - name: Build VyOS Generic ISO
        run: |
          cd vyos-build
          docker run --rm -v $PWD:/vyos -w /vyos vyos/vyos-build:current bash -c "
            apt-get update && apt-get install -y ca-certificates sudo
            update-ca-certificates
            make iso
          "          
      - name: Convert ISO to tar.gz
        run: |
          cd vyos-build/build
          ISO_FILE=$(ls vyos-*.iso | head -n 1)
          TAR_FILE=\"${ISO_FILE%.iso}.tar.gz\"
          echo \"Compressing $ISO_FILE into $TAR_FILE\"
          tar -czvf \"$TAR_FILE\" \"$ISO_FILE\"
          
#      - name: Upload VyOS ISO
#        uses: actions/upload-artifact@v4
#        with:
#          name: vyos-nightly-iso
#          path: vyos-build/build/*.iso
          
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Upload VyOS ISO tarball to GCS
        run: |
          cd vyos-build/build
          FILE=$(ls vyos-*.tar.gz | head -n 1)
          echo \"Uploading $FILE to gs://${GCS_BUCKET}/\"
          gsutil cp \"$FILE\" \"gs://${GCS_BUCKET}/\"

